class Contrato_Cap(object):
 def __init__(self,CD_CONTRATO=None,DT_EMISSAO=None,NO_REVISAO_EFETIVADA=None,NO_REVISAO_CORRENTE=None,CD_SITUACAO=None,VL_TOTAL_LIBERACOES=None,VL_SALDO_PRINCIPAL=None,VL_SALDO_JUROS=None,FL_DEVGARANTIA=None,DC_OBSGARANTIA=None):
 	self.CD_CONTRATO = CD_CONTRATO # <type 'cx_Oracle.STRING'>
	self.DT_EMISSAO = DT_EMISSAO # <type 'cx_Oracle.DATETIME'>
	self.NO_REVISAO_EFETIVADA = NO_REVISAO_EFETIVADA # <type 'cx_Oracle.NUMBER'>
	self.NO_REVISAO_CORRENTE = NO_REVISAO_CORRENTE # <type 'cx_Oracle.NUMBER'>
	self.CD_SITUACAO = CD_SITUACAO # <type 'cx_Oracle.FIXED_CHAR'>
	self.VL_TOTAL_LIBERACOES = VL_TOTAL_LIBERACOES # <type 'cx_Oracle.NUMBER'>
	self.VL_SALDO_PRINCIPAL = VL_SALDO_PRINCIPAL # <type 'cx_Oracle.NUMBER'>
	self.VL_SALDO_JUROS = VL_SALDO_JUROS # <type 'cx_Oracle.NUMBER'>
	self.FL_DEVGARANTIA = FL_DEVGARANTIA # <type 'cx_Oracle.FIXED_CHAR'>
	self.DC_OBSGARANTIA = DC_OBSGARANTIA # <type 'cx_Oracle.STRING'>
 def getCD_CONTRATO(self):
  return self.CD_CONTRATO
 def getDT_EMISSAO(self):
  return self.DT_EMISSAO
 def getNO_REVISAO_EFETIVADA(self):
  return self.NO_REVISAO_EFETIVADA
 def getNO_REVISAO_CORRENTE(self):
  return self.NO_REVISAO_CORRENTE
 def getCD_SITUACAO(self):
  return self.CD_SITUACAO
 def getVL_TOTAL_LIBERACOES(self):
  return self.VL_TOTAL_LIBERACOES
 def getVL_SALDO_PRINCIPAL(self):
  return self.VL_SALDO_PRINCIPAL
 def getVL_SALDO_JUROS(self):
  return self.VL_SALDO_JUROS
 def getFL_DEVGARANTIA(self):
  return self.FL_DEVGARANTIA
 def getDC_OBSGARANTIA(self):
  return self.DC_OBSGARANTIA
 def setCD_CONTRATO(self,CD_CONTRATO):
   self.CD_CONTRATO = CD_CONTRATO
 def setDT_EMISSAO(self,DT_EMISSAO):
   self.DT_EMISSAO = DT_EMISSAO
 def setNO_REVISAO_EFETIVADA(self,NO_REVISAO_EFETIVADA):
   self.NO_REVISAO_EFETIVADA = NO_REVISAO_EFETIVADA
 def setNO_REVISAO_CORRENTE(self,NO_REVISAO_CORRENTE):
   self.NO_REVISAO_CORRENTE = NO_REVISAO_CORRENTE
 def setCD_SITUACAO(self,CD_SITUACAO):
   self.CD_SITUACAO = CD_SITUACAO
 def setVL_TOTAL_LIBERACOES(self,VL_TOTAL_LIBERACOES):
   self.VL_TOTAL_LIBERACOES = VL_TOTAL_LIBERACOES
 def setVL_SALDO_PRINCIPAL(self,VL_SALDO_PRINCIPAL):
   self.VL_SALDO_PRINCIPAL = VL_SALDO_PRINCIPAL
 def setVL_SALDO_JUROS(self,VL_SALDO_JUROS):
   self.VL_SALDO_JUROS = VL_SALDO_JUROS
 def setFL_DEVGARANTIA(self,FL_DEVGARANTIA):
   self.FL_DEVGARANTIA = FL_DEVGARANTIA
 def setDC_OBSGARANTIA(self,DC_OBSGARANTIA):
  self.DC_OBSGARANTIA = DC_OBSGARANTIA
 def atributos(self):
  return ['setCD_CONTRATO', 'setDT_EMISSAO', 'setNO_REVISAO_EFETIVADA', 'setNO_REVISAO_CORRENTE', 'setCD_SITUACAO', 'setVL_TOTAL_LIBERACOES', 'setVL_SALDO_PRINCIPAL', 'setVL_SALDO_JUROS', 'setFL_DEVGARANTIA', 'setDC_OBSGARANTIA']